//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsGSM.GameServer.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsGSM.GameServer.Data.Icon", typeof(Icon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/eco.png 的本地化字符串。
        /// </summary>
        public static string Eco_专用服务器 {
            get {
                return ResourceManager.GetString("Eco 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/onset.png 的本地化字符串。
        /// </summary>
        public static string Onset_专用服务器 {
            get {
                return ResourceManager.GetString("Onset 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hl2dm.png 的本地化字符串。
        /// </summary>
        public static string Source_SDK_Base_2013_专用服务器 {
            get {
                return ResourceManager.GetString("Source SDK Base 2013 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/7dtd.png 的本地化字符串。
        /// </summary>
        public static string 七日杀_专用服务器 {
            get {
                return ResourceManager.GetString("七日杀 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/gta5.png 的本地化字符串。
        /// </summary>
        public static string 侠盗猎车手V_专用服务器 {
            get {
                return ResourceManager.GetString("侠盗猎车手V 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/zps.png 的本地化字符串。
        /// </summary>
        public static string 僵尸恐慌_专用服务器 {
            get {
                return ResourceManager.GetString("僵尸恐慌 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dayz.png 的本地化字符串。
        /// </summary>
        public static string 僵尸末日_专用服务器 {
            get {
                return ResourceManager.GetString("僵尸末日 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tfc.png 的本地化字符串。
        /// </summary>
        public static string 军团要塞_经典_专用服务器 {
            get {
                return ResourceManager.GetString("军团要塞:经典 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tf2.png 的本地化字符串。
        /// </summary>
        public static string 军团要塞2_专用服务器 {
            get {
                return ResourceManager.GetString("军团要塞2 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hlof.png 的本地化字符串。
        /// </summary>
        public static string 半条命_针锋相对_专用服务器 {
            get {
                return ResourceManager.GetString("半条命:针锋相对 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hl2dm.png 的本地化字符串。
        /// </summary>
        public static string 半条命2_死亡竞赛_专用服务器 {
            get {
                return ResourceManager.GetString("半条命2:死亡竞赛 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/cs.png 的本地化字符串。
        /// </summary>
        public static string 反恐精英_1_6_专用服务器 {
            get {
                return ResourceManager.GetString("反恐精英:1.6 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/csgo.png 的本地化字符串。
        /// </summary>
        public static string 反恐精英_全球攻势_专用服务器 {
            get {
                return ResourceManager.GetString("反恐精英:全球攻势 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/css.png 的本地化字符串。
        /// </summary>
        public static string 反恐精英_起源_专用服务器 {
            get {
                return ResourceManager.GetString("反恐精英:起源 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/cscz.png 的本地化字符串。
        /// </summary>
        public static string 反恐精英_零点行动_专用服务器 {
            get {
                return ResourceManager.GetString("反恐精英-零点行动 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ins.png 的本地化字符串。
        /// </summary>
        public static string 叛乱_专用服务器 {
            get {
                return ResourceManager.GetString("叛乱 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/inss.png 的本地化字符串。
        /// </summary>
        public static string 叛乱_沙漠风暴_专用服务器 {
            get {
                return ResourceManager.GetString("叛乱:沙漠风暴 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rok.png 的本地化字符串。
        /// </summary>
        public static string 君临天下_专用服务器 {
            get {
                return ResourceManager.GetString("君临天下 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/nmrih.png 的本地化字符串。
        /// </summary>
        public static string 地狱已满_专用服务器 {
            get {
                return ResourceManager.GetString("地狱已满 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/vts.png 的本地化字符串。
        /// </summary>
        public static string 复古物语_专用服务器 {
            get {
                return ResourceManager.GetString("复古物语 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/se.png 的本地化字符串。
        /// </summary>
        public static string 太空工程师_专用服务器 {
            get {
                return ResourceManager.GetString("太空工程师 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/egs.png 的本地化字符串。
        /// </summary>
        public static string 帝国霸业_银河生存_专用服务器 {
            get {
                return ResourceManager.GetString("帝国霸业-银河生存 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mc.png 的本地化字符串。
        /// </summary>
        public static string 我的世界__Java版服务器 {
            get {
                return ResourceManager.GetString("我的世界: Java版服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mcbe.png 的本地化字符串。
        /// </summary>
        public static string 我的世界__基岩版服务器 {
            get {
                return ResourceManager.GetString("我的世界: 基岩版服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mcpe.png 的本地化字符串。
        /// </summary>
        public static string 我的世界__携带版服务器__PocketMine_MP_ {
            get {
                return ResourceManager.GetString("我的世界: 携带版服务器 (PocketMine-MP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ps.png 的本地化字符串。
        /// </summary>
        public static string 战争附言_专用服务器 {
            get {
                return ResourceManager.GetString("战争附言 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/sq.png 的本地化字符串。
        /// </summary>
        public static string 战术小队_专用服务器 {
            get {
                return ResourceManager.GetString("战术小队 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/arkse.png 的本地化字符串。
        /// </summary>
        public static string 方舟_生存计划_专用服务器 {
            get {
                return ResourceManager.GetString("方舟:生存计划 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/unt.png 的本地化字符串。
        /// </summary>
        public static string 未转变者_专用服务器 {
            get {
                return ResourceManager.GetString("未转变者 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tf.png 的本地化字符串。
        /// </summary>
        public static string 森林_专用服务器 {
            get {
                return ResourceManager.GetString("森林 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/sotf.png 的本地化字符串。
        /// </summary>
        public static string 森林之子_专用服务器 {
            get {
                return ResourceManager.GetString("森林之子 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dmc.png 的本地化字符串。
        /// </summary>
        public static string 死亡竞赛经典版_专用服务器 {
            get {
                return ResourceManager.GetString("死亡竞赛经典版 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/l4d2.png 的本地化字符串。
        /// </summary>
        public static string 求生之路2_专用服务器 {
            get {
                return ResourceManager.GetString("求生之路2 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ce.png 的本地化字符串。
        /// </summary>
        public static string 流放者柯南_专用服务器 {
            get {
                return ResourceManager.GetString("流放者柯南 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/bt.png 的本地化字符串。
        /// </summary>
        public static string 潜渊症_专用服务器 {
            get {
                return ResourceManager.GetString("潜渊症 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/heat.png 的本地化字符串。
        /// </summary>
        public static string 热能标记_专用服务器 {
            get {
                return ResourceManager.GetString("热能标记 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/avorion.png 的本地化字符串。
        /// </summary>
        public static string 猎户座_专用服务器 {
            get {
                return ResourceManager.GetString("猎户座 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/gmod.png 的本地化字符串。
        /// </summary>
        public static string 盖瑞模组_专用服务器 {
            get {
                return ResourceManager.GetString("盖瑞模组 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dod.png 的本地化字符串。
        /// </summary>
        public static string 胜利之日_专用服务器 {
            get {
                return ResourceManager.GetString("胜利之日 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dods.png 的本地化字符串。
        /// </summary>
        public static string 胜利之日_起源_专用服务器 {
            get {
                return ResourceManager.GetString("胜利之日:起源 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rust.png 的本地化字符串。
        /// </summary>
        public static string 腐蚀_专用服务器 {
            get {
                return ResourceManager.GetString("腐蚀 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/vm.png 的本地化字符串。
        /// </summary>
        public static string 英灵神殿_专用服务器 {
            get {
                return ResourceManager.GetString("英灵神殿 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/olow.png 的本地化字符串。
        /// </summary>
        public static string 西部狂徒_专用服务器 {
            get {
                return ResourceManager.GetString("西部狂徒 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rcc.png 的本地化字符串。
        /// </summary>
        public static string 跳跃袭击_专用服务器 {
            get {
                return ResourceManager.GetString("跳跃袭击 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ror2.png 的本地化字符串。
        /// </summary>
        public static string 雨中冒险2_专用服务器 {
            get {
                return ResourceManager.GetString("雨中冒险2 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mordhau.png 的本地化字符串。
        /// </summary>
        public static string 雷霆一击_专用服务器 {
            get {
                return ResourceManager.GetString("雷霆一击 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/sw.png 的本地化字符串。
        /// </summary>
        public static string 风暴工程_专用服务器 {
            get {
                return ResourceManager.GetString("风暴工程 专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/bw.png 的本地化字符串。
        /// </summary>
        public static string 黑色艉流_专用服务器 {
            get {
                return ResourceManager.GetString("黑色艉流 专用服务器", resourceCulture);
            }
        }
    }
}
