//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsGSM.GameServer.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsGSM.GameServer.Data.Icon", typeof(Icon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/arkse.png 的本地化字符串。
        /// </summary>
        public static string ARK__方舟生存计划专用服务器 {
            get {
                return ResourceManager.GetString("ARK: 方舟生存计划专用服务器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/avorion.png 的本地化字符串。
        /// </summary>
        public static string Avorion_Dedicated_Server {
            get {
                return ResourceManager.GetString("Avorion Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/bt.png 的本地化字符串。
        /// </summary>
        public static string Barotrauma_Dedicated_Server {
            get {
                return ResourceManager.GetString("Barotrauma Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/bw.png 的本地化字符串。
        /// </summary>
        public static string BlackWake_Dedicated_Server {
            get {
                return ResourceManager.GetString("BlackWake Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ce.png 的本地化字符串。
        /// </summary>
        public static string Conan_Exiles_Dedicated_Server {
            get {
                return ResourceManager.GetString("Conan Exiles Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/cs.png 的本地化字符串。
        /// </summary>
        public static string Counter_Strike__1_6_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: 1.6 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/cscz.png 的本地化字符串。
        /// </summary>
        public static string Counter_Strike__Condition_Zero_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Condition Zero Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/csgo.png 的本地化字符串。
        /// </summary>
        public static string Counter_Strike__Global_Offensive_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Global Offensive Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/css.png 的本地化字符串。
        /// </summary>
        public static string Counter_Strike__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dods.png 的本地化字符串。
        /// </summary>
        public static string Day_of_Defeat__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dod.png 的本地化字符串。
        /// </summary>
        public static string Day_of_Defeat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dayz.png 的本地化字符串。
        /// </summary>
        public static string DayZ_Dedicated_Server {
            get {
                return ResourceManager.GetString("DayZ Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/dmc.png 的本地化字符串。
        /// </summary>
        public static string Deathmatch_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Deathmatch Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/eco.png 的本地化字符串。
        /// </summary>
        public static string Eco_Dedicated_Server {
            get {
                return ResourceManager.GetString("Eco Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/egs.png 的本地化字符串。
        /// </summary>
        public static string Empyrion___Galactic_Survival_Dedicated_Server {
            get {
                return ResourceManager.GetString("Empyrion - Galactic Survival Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/gmod.png 的本地化字符串。
        /// </summary>
        public static string Garry_s_Mod_Dedicated_Server {
            get {
                return ResourceManager.GetString("Garry\'s Mod Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/gta5.png 的本地化字符串。
        /// </summary>
        public static string Grand_Theft_Auto_V_Dedicated_Server__FiveM_ {
            get {
                return ResourceManager.GetString("Grand Theft Auto V Dedicated Server (FiveM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hlof.png 的本地化字符串。
        /// </summary>
        public static string Half_Life__Opposing_Force_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life: Opposing Force Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hl2dm.png 的本地化字符串。
        /// </summary>
        public static string Half_Life_2__Deathmatch_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life 2: Deathmatch Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/heat.png 的本地化字符串。
        /// </summary>
        public static string Heat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Heat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/inss.png 的本地化字符串。
        /// </summary>
        public static string Insurgency__Sandstorm_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency: Sandstorm Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ins.png 的本地化字符串。
        /// </summary>
        public static string Insurgency_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/l4d2.png 的本地化字符串。
        /// </summary>
        public static string Left_4_Dead_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Left 4 Dead 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mcbe.png 的本地化字符串。
        /// </summary>
        public static string Minecraft__Bedrock_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Bedrock Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mc.png 的本地化字符串。
        /// </summary>
        public static string Minecraft__Java_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Java Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mcpe.png 的本地化字符串。
        /// </summary>
        public static string Minecraft__Pocket_Edition_Server__PocketMine_MP_ {
            get {
                return ResourceManager.GetString("Minecraft: Pocket Edition Server (PocketMine-MP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/mordhau.png 的本地化字符串。
        /// </summary>
        public static string Mordhau_Dedicated_Server {
            get {
                return ResourceManager.GetString("Mordhau Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/nmrih.png 的本地化字符串。
        /// </summary>
        public static string No_More_Room_in_Hell_Dedicated_Server {
            get {
                return ResourceManager.GetString("No More Room in Hell Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/onset.png 的本地化字符串。
        /// </summary>
        public static string Onset_Dedicated_Server {
            get {
                return ResourceManager.GetString("Onset Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/olow.png 的本地化字符串。
        /// </summary>
        public static string Outlaws_of_the_Old_West_Dedicated_Server {
            get {
                return ResourceManager.GetString("Outlaws of the Old West Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ps.png 的本地化字符串。
        /// </summary>
        public static string Post_Scriptum_Dedicated_Server {
            get {
                return ResourceManager.GetString("Post Scriptum Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rok.png 的本地化字符串。
        /// </summary>
        public static string Reign_Of_Kings_Dedicated_Server {
            get {
                return ResourceManager.GetString("Reign Of Kings Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rcc.png 的本地化字符串。
        /// </summary>
        public static string Ricochet_Dedicated_Server {
            get {
                return ResourceManager.GetString("Ricochet Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/ror2.png 的本地化字符串。
        /// </summary>
        public static string Risk_of_Rain_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Risk of Rain 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/rust.png 的本地化字符串。
        /// </summary>
        public static string Rust_Dedicated_Server {
            get {
                return ResourceManager.GetString("Rust Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/hl2dm.png 的本地化字符串。
        /// </summary>
        public static string Source_SDK_Base_2013_Dedicated_Server {
            get {
                return ResourceManager.GetString("Source SDK Base 2013 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/se.png 的本地化字符串。
        /// </summary>
        public static string Space_Engineers_Dedicated_Server {
            get {
                return ResourceManager.GetString("Space Engineers Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/sq.png 的本地化字符串。
        /// </summary>
        public static string Squad_Dedicated_Server {
            get {
                return ResourceManager.GetString("Squad Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/sw.png 的本地化字符串。
        /// </summary>
        public static string Stormworks_Dedicated_Server {
            get {
                return ResourceManager.GetString("Stormworks Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tf2.png 的本地化字符串。
        /// </summary>
        public static string Team_Fortress_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tfc.png 的本地化字符串。
        /// </summary>
        public static string Team_Fortress_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/tf.png 的本地化字符串。
        /// </summary>
        public static string The_Forest_Dedicated_Server {
            get {
                return ResourceManager.GetString("The Forest Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/unt.png 的本地化字符串。
        /// </summary>
        public static string Unturned_Dedicated_Server {
            get {
                return ResourceManager.GetString("Unturned Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/vts.png 的本地化字符串。
        /// </summary>
        public static string Vintage_Story_Dedicated_Server {
            get {
                return ResourceManager.GetString("Vintage Story Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/zps.png 的本地化字符串。
        /// </summary>
        public static string Zombie_Panic_Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Zombie Panic Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images/Games/7dtd.png 的本地化字符串。
        /// </summary>
        public static string 七日杀专用服务器 {
            get {
                return ResourceManager.GetString("七日杀专用服务器", resourceCulture);
            }
        }
    }
}
